name: Сборка и загрузка Docker-образа

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v3  

      - name: Вход в Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Сборка и загрузка Docker-образа
        uses: docker/build-push-action@v4
        with:
          context: src  
          file: src/Dockerfile
          push: true 
          tags: et3rnaldespair/cloudtask-hse-nis:latest 